version: 2.1

jobs:
  verify-config:
    docker:
      - image: alexfalkowski/config:1.8
    working_directory: ~/app-config
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make lint
      - run: make token
      - run: make verify
    resource_class: large
  release:
    docker:
      - image: alexfalkowski/release:3.9
    working_directory: ~/app-config
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: release
    resource_class: large

workflows:
  app-config:
    jobs:
      - verify-config
      - release:
          context: gh
          requires:
            - verify-config
          filters:
            branches:
              only: master
